
name: call_me

on:
  workflow_call:
    inputs:
      favorite_superhero:
        required: true
        type: string
      second_favorite_superhero:
        required: true
        type: string

jobs:
  repo_list_dir:
    runs-on: [self-hosted] 
    steps:
      - name: checkout_repo
        uses: actions/checkout@v3
    
      - name: list directory
        run: |
          ls -la

  favorite_superhero_show_1_1:
    runs-on:  [self-hosted] 
    environment: Manual_1
    steps:
      - name: checkout_repo
        uses: actions/checkout@v3
    
      - name: show favorite superhero
        run: |
          echo "This is my favorite Superhero ... ${{ inputs.favorite_superhero }}"
          echo " "
          echo "This is my second favorite Superhero  ... ${{ inputs.second_favorite_superhero }}"
    needs: repo_list_dir

  favorite_superhero_show_1_2:
    runs-on: [self-hosted] 
    environment: Manual_1
    steps:
      - name: checkout_repo
        uses: actions/checkout@v3
    
      - name: show favorite superhero
        run: |
          echo "This is my favorite Superhero ... ${{ inputs.favorite_superhero }}"
          echo " "
          echo "This is my second favorite Superhero  ... ${{ inputs.second_favorite_superhero }}"
    needs: favorite_superhero_show_1_1

  favorite_superhero_show_2_1:
    runs-on: [self-hosted] 
    environment: Manual_2
    steps:
      - name: checkout_repo
        uses: actions/checkout@v3
    
      - name: show favorite superhero
        run: |
          echo "This is my favorite Superhero ... ${{ inputs.favorite_superhero }}"
          echo " "
          echo "This is my second favorite Superhero  ... ${{ inputs.second_favorite_superhero }}"
    needs: repo_list_dir

  favorite_superhero_show_2_2:
    runs-on: [self-hosted] 
    environment: Manual_2
    steps:
      - name: checkout_repo
        uses: actions/checkout@v3
    
      - name: show favorite superhero
        run: |
          echo "This is my favorite Superhero ... ${{ inputs.favorite_superhero }}"
          echo " "
          echo "This is my second favorite Superhero  ... ${{ inputs.second_favorite_superhero }}"
    needs: favorite_superhero_show_2_1