
name: cm-2

on:
  workflow_call:
    inputs:
      favorite-superhero:
        required: true
        type: string
      second-favorite-superhero:
        required: true
        type: string

jobs:
  repo-list-dir:
    runs-on: [self-hosted] 
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
    
      - name: list directory
        run: |
          ls -la

  fav-super-3-1:
    runs-on:  [self-hosted] 
    environment: Manual-3-1
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
    
      - name: show favorite superhero
        run: |
          echo "This is my favorite Superhero ... ${{ inputs.favorite-superhero }}"
          echo " "
          echo "This is my second favorite Superhero  ... ${{ inputs.second-favorite-superhero }}"
    needs: repo-list-dir

  fav-super-3-2:
    runs-on: [self-hosted] 
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
    
      - name: show favorite superhero
        run: |
          echo "This is my favorite Superhero ... ${{ inputs.favorite-superhero }}"
          echo " "
          echo "This is my second favorite Superhero  ... ${{ inputs.second-favorite-superhero }}"
    needs: fav-super-3-1

  fav-super-4-1:
    runs-on: [self-hosted] 
    environment: Manual-4-1
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
    
      - name: show favorite superhero
        run: |
          echo "This is my favorite Superhero ... ${{ inputs.favorite-superhero }}"
          echo " "
          echo "This is my second favorite Superhero  ... ${{ inputs.second-favorite-superhero }}"
    needs: repo-list-dir

  fav-super-4-2:
    runs-on: [self-hosted] 
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
    
      - name: show favorite superhero
        run: |
          echo "This is my favorite Superhero ... ${{ inputs.favorite-superhero }}"
          echo " "
          echo "This is my second favorite Superhero  ... ${{ inputs.second-favorite-superhero }}"
    needs: fav-super-4-1
