
name: k8s-get-nodes

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      aws-subscription:
        required: true
        type: string
      cluster-name:
        required: true
        type: string
      iam-identity:
        required: true
        type: string

jobs:
  pull-image:
    runs-on: [self-hosted, maint-only-01] 
    steps:
      - name: output_image_pulling
        shell: bash
        run: |
          echo "----- docker image getting pulled -----"
          echo "${{ inputs.aws-subscription }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/admin-${{ inputs.cluster-name }}:latest"
      - name: checkout-repo-local
        uses: actions/checkout@v3
      - name: checkout-devops-central-actions
        uses: actions/checkout@v3
        with:
          repository: crewshotel/devops-central-actions
          token: ${{ secrets.ACTIONS_PIPELINE }}
          path: devops-central-actions
      - name: set-aws-credentials
        shell: bash
        if: ${{ inputs.iam-identity == 'eks_mgmt' }}
        run: |
          chmod +x ./devops-central-actions/scripts/aws/config/set-id-key-eks-mgmt.sh
          ./devops-central-actions/scripts/aws/config/set-id-key-eks-mgmt.sh ${{ secrets.AWS_ID_EKS_MGMT }} ${{ secrets.AWS_KEY_EKS_MGMT }}
      - name: docker-pull
        shell: bash
        run: |
          chmod +x ./devops-central-actions/scripts/aws/docker/pull-admin-eks-cluster.sh
          ./devops-central-actions/scripts/aws/docker/pull-admin-eks-cluster.sh ${{ inputs.aws-subscription }} ${{ inputs.aws-region}} ${{ inputs.cluster-name }}
  qry-k8s-nodes:
    runs-on [self-hosted, maint-only-01]
      steps:
      - name: output_image_starting
        shell: bash
        run: |
          echo "----- docker image starting -----"
          echo "${{ inputs.aws-subscription }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/admin-${{ inputs.cluster-name }}:latest"
      - name: qry-k8s-cluster-nodes
        shell: bash
        run: |
          chmod +x ./devops-central-actions/scripts/aws/docker/qry-k8s-cluster-nodes.sh
          ./devops-central-actions/scripts/aws/docker/qry-k8s-cluster-nodes.sh ${{ inputs.aws-subscription }} ${{ inputs.aws-region}} ${{ inputs.cluster-name }}
           
      