
name: kubectl-get-nodes

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      aws-subscription:
        required: true
        type: string
      cluster-name:
        required: true
        type: string
      iam-identity:
        required: true
        type: string

jobs:
  d-pull-i-1:
    runs-on: [self-hosted] 
    steps:
      - name: checkout-repo-local
        uses: actions/checkout@v3
      - name: checkout-devops-central-actions
        uses: actions/checkout@v3
        with:
          repository: crewshotel/devops-central-actions
          token: ${{ secrets.ACTIONS_PIPELINE }}
          path: devops-central-actions
      - name: list-folder-contents
        run: |
          ls -la ./devops-central-actions
      - name: set-aws-credentials
        shell: bash
        run: |
            chmod +x ./devops-central-actions/scripts/aws/config/set-id-key-eks_mgmt.sh
            ./devops-central-actions/scripts/aws/config/set-id-key-eks_mgmt.sh ${{ secrets.AWS_ID_EKS_MGMT }} ${{ secrets.AWS_KEY_EKS_MGMT }}
          fi
      - name: docker-pull
        run: |
           chmod +x /home/ec2-user/actions-runner/_work/devops-test-01/devops-test-01/devops-central-actions/scripts/aws/docker/admin-eks-cluster.sh
           echo "sub - region - cluster - ${{ inputs.aws-subscription }} ${{ inputs.aws-region}} ${{ inputs.cluster-name }}"
           /home/ec2-user/actions-runner/_work/devops-test-01/devops-test-01/devops-central-actions/scripts/aws/docker/admin-eks-cluster.sh ${{ inputs.aws-subscription }} ${{ inputs.aws-region}} ${{ inputs.cluster-name }}
        shell: bash
